export const LARGE_SCREEN_ADDENDUM = 3;
export const MIDDLE_SCREEN_ADDENDUM = 2;
export const SMALL_SCREEN_ADDENDUM = 2;

export const LARGE_SCREEN_INITIAL_CARDS = 12;
export const MIDDLE_SCREEN_INITIAL_CARDS = 8;
export const SMALL_SCREEN_INITIAL_CARDS = 5;